link:
  home: "https://www.railstutorial.org/"
  learn: "https://www.learnenough.com/"
  link_screen_casts: "https://screencasts.railstutorial.org/"
  link_contact: "https://www.railstutorial.org/contact/"
  link_help: "https://www.railstutorial.org/help"
